export enum ErrorCodes {
  // General errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  
  // OCR specific errors
  OCR_PROCESSING_FAILED = 'OCR_PROCESSING_FAILED',
  OCR_INCOMPLETE_DATA = 'OCR_INCOMPLETE_DATA',
  OCR_INVALID_IMAGE = 'OCR_INVALID_IMAGE',
  
  // Database errors
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_OPERATION_FAILED = 'DATABASE_OPERATION_FAILED',
  DUPLICATE_RECORD = 'DUPLICATE_RECORD',
  
  // File upload errors
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  MISSING_FILES = 'MISSING_FILES',
  
  // Validation errors
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_AADHAAR_NUMBER = 'INVALID_AADHAAR_NUMBER',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
  INVALID_NAME_FORMAT = 'INVALID_NAME_FORMAT',
}

